# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

name: Run Makefile

on:
  push:

  pull_request:

  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install ldid

      - name: Compile
        run: make
      
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: magiccfg
          path: packages/magiccfg.ipa
